In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor

In [ ]:
df = pd.DataFrame({'min_temp':[20,21,22.3,34],'max_temp':[21,23,24.5,35]})

In [ ]:
df.head()

min_temp  max_temp
0      20.0      21.0
1      21.0      23.0
2      22.3      24.5
3      34.0      35.0

In [ ]:
X = df[['min_temp']]
y = df[['max_temp']]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(2),activation='relu',max_iter=1000)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=2, max_iter=1000)

In [ ]:
iter = 2
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[-2.40962987e-04 -4.19151980e-01]]
[-0.69194288 -1.25785939]
[[ 0.5598652 ]
 [-0.00099335]]
[2.34534751]
[[1.62713073e-04 1.67437250e+00]]
[-1.06360904  0.42454429]
[[1.74741244e-14]
 [7.17558540e-01]]
[-0.18637619]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
df = pd.DataFrame({'even':[2,4,6,8,10],'odd':[1,3,5,7,9]})

In [ ]:
df.head()

even  odd
0     2    1
1     4    3
2     6    5
3     8    7
4    10    9

In [ ]:
X = df[['even']]
y = df[['odd']]

In [ ]:
scalar = StandardScaler()
X_scaled = scalar.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(4),activation='relu',max_iter=500)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=4, max_iter=500)

In [ ]:
iter = 2
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 1.03766781]
 [-0.73531197]
 [-0.00264712]
 [ 0.94994021]]
[0.99961163]
[[ 1.36653897 -0.08011826  0.00367284  1.11715135]]
[ 0.31808346 -0.11176081 -0.73396642  0.15309392]
[[-0.45304209]
 [ 0.09585486]
 [-0.3395549 ]
 [ 1.10569083]]
[0.66114377]
[[ 3.12820358e-04 -8.09857457e-01 -9.92605010e-07 -8.98545076e-01]]
[-0.4828381  -1.17750149 -0.71861558 -0.05795254]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = c

[[ 3.87465217e-01]
 [ 5.45968833e-13]
 [-6.19542058e-02]
 [-6.47036768e-01]]
[1.0696931]
[[-6.06287809e-02 -1.83759605e-04 -4.90167679e-01 -1.82723984e-01]]
[-0.88524603 -0.59288423  0.34657424  0.09516717]
[[1.31298044]
 [0.06458393]
 [0.15943205]
 [0.85219346]]
[-0.41486602]
[[ 9.93547778e-01  4.71130070e-13 -2.88279535e-01  6.21803324e-01]]
[ 0.44029505 -1.03414978  0.86193501  0.77295715]


/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
df = pd.DataFrame({'Day':[1,2,3,4,5],'night':[6,7,8,9,10]})

In [ ]:
df.head()

Day  night
0    1      6
1    2      7
2    3      8
3    4      9
4    5     10

In [ ]:
X = df[['Day']]
y = df[['night']]

In [ ]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [ ]:
mlp = MLPRegressor(hidden_layer_sizes=(5),activation='relu',max_iter=10)

In [ ]:
mlp.fit(X_scaled,y)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPRegressor(hidden_layer_sizes=5, max_iter=10)

In [ ]:
iter = 5
for i in range(iter):
  mlp.fit(X_scaled,y)
  hidden_layer_weights = mlp.coefs_[0]
  hidden_layer_bias = mlp.intercepts_[0]
  output_layer_weights = mlp.coefs_[1]
  output_layer_bias = mlp.intercepts_[1]
  print(hidden_layer_weights)
  print(hidden_layer_bias)
  print(output_layer_weights)
  print(output_layer_bias)

[[-0.34962737 -0.26043818  0.41108966 -0.27855517  0.76563004]]
[-0.3350404   0.58449882  0.12818391  0.26994813  0.15652508]
[[ 0.68582722]
 [-0.06046776]
 [-0.05844274]
 [ 0.94871183]
 [ 0.42174045]]
[0.85603924]
[[ 0.47481173 -0.51490001  0.92146237  0.62090981 -0.66520336]]
[0.20250981 0.18899791 0.45395839 0.55438588 0.93457899]
[[ 0.15868185]
 [ 0.4035107 ]
 [-0.05499188]
 [ 0.04988153]
 [-0.45763246]]
[0.61388677]
[[0.40643787 0.97812359 0.76316728 0.33134962 0.20763398]]
[ 0.83285051  0.93991224 -0.67568615 -0.77632216  0.10686105]
[[ 0.16151183]
 [-0.3225013 ]
 [-0.74606132]
 [-0.87501919]
 [-0.12674523]]
[-0.20980713]
[[-0.67770536  0.87035892 -0.48035394 -0.92645242 -0.16599037]]
[-0.09839588 -0.1010769   0.99181504 -0.88417771  0.18736916]
[[-0.90328433]
 [ 0.16816752]
 [ 0.35886688]
 [-0.77773131]
 [-0.82329547]]
[0.74095944]
[[-0.69780585  0.22817156 -0.90838106 -0.32764554  0.31347542]]
[ 0.02622146 -0.5853117   0.40776737  0.01882635  0.51010212]
[[-0.01521033]
 [ 0.218

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converged yet.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:1625: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (10) reached and the optimization hasn't converge

In [ ]:
from mlxtend.data import iris_data
from mlxtend.plotting import plot_decision_regions
import matplotlib.pyplot as plt
from mlxtend.classifier import Perceptron
import numpy as np

In [ ]:
X,y = iris_data()

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X = X[:,[0,3]]

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
X = X[0:100]
y = y[0:100]

In [ ]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
X[:,0] = (X[:,0]-X[:,0].mean())/X[:,0].std()
X[:,1] = (X[:,1]-X[:,1].mean())/X[:,1].std()

In [ ]:
X

array([[-0.5810659 ,  0.85713543,  1.4       ,  0.2       ],
       [-0.89430898, -0.19845007,  1.4       ,  0.2       ],
       [-1.20755205,  0.22378413,  1.3       ,  0.2       ],
       [-1.36417359,  0.01266703,  1.5       ,  0.2       ],
       [-0.73768744,  1.06825253,  1.4       ,  0.2       ],
       [-0.11120129,  1.70160383,  1.7       ,  0.4       ],
       [-1.36417359,  0.64601833,  1.4       ,  0.3       ],
       [-0.73768744,  0.64601833,  1.5       ,  0.2       ],
       [-1.67741667, -0.40956718,  1.4       ,  0.2       ],
       [-0.89430898,  0.01266703,  1.5       ,  0.1       ],
       [-0.11120129,  1.27936963,  1.5       ,  0.2       ],
       [-1.05093052,  0.64601833,  1.6       ,  0.2       ],
       [-1.05093052, -0.19845007,  1.4       ,  0.1       ],
       [-1.8340382 , -0.19845007,  1.1       ,  0.1       ],
       [ 0.51528486,  1.91272093,  1.2       ,  0.2       ],
       [ 0.35866332,  2.75718933,  1.5       ,  0.4       ],
       [-0.11120129,  1.

In [ ]:
pn = Perceptron(epochs =5,eta=0.05,random_seed=0)
pn.fit(X,y)

In [ ]:
print('weights',pn.w_)


weights [[ 0.41577247]
 [-0.25187235]
 [ 0.05978738]
 [ 0.07240893]]


In [ ]:
print('bias',pn.b_)

bias [-0.2]


In [ ]:
def perceptron_ex(X,weights,bias):
  output = np.dot(X,weights)+bias
  return np.where(output>=0.0,1,0)

In [ ]:
X_new = np.array([[0.5,-1.0]])
perceptron_ex(X_new,pn.w_,pn.b_)

ValueError: shapes (1,2) and (4,1) not aligned: 2 (dim 1) != 4 (dim 0)